import random 
import time

#volba = ["Skrz mřížku u dveří jsi uviděl stvoření, které nepřipomína člověka a rozhodl jsi se od dveří utéct zpět do chodby." , "Byla to jen krysa, která shodila krabice. Rozhodl jsi se pokračovat chodbou."]
#value = random.choice(volba)

#uvod
jmeno =input("Zadejte své jméno: ")
print(f"Zdravíčko {jmeno} a vítejte v tomto hororvém příběhu.")
time.sleep(2)
print("Srdečně vás vítám u hry:    Do soumraku\n")

#spusteni/nespusteni hry

spusteni = input("Chtěli by jste tuto hru spustit nebo raději opustit ?")
if spusteni == "spustit" :
    print("Pojďme se vrhnout do tohoto hororového příběhu.")
    time.sleep(2)
    print("Jedno podzimní odpoledne jste se rozhodli s pár kamarády prozkoumat dlouhá léta opuštěnou starou psychiatrickou léčebnu. ") 
    time.sleep(2)
    print("Počas této prozkoumávačky jste se dostali až do sklepení, kde vás neznámá entita napadla zezadu a plynem omámila.")
    time.sleep(2)
    print("Poté co jste se probral, tak jste byl úplně sám ve sklepení v jedné z místností.")
    time.sleep(2)
    print("Naštěstí jste nebyl poraněn ani spoután, ale bylo vám jasné, že musíte okamžitě konat. ")
    time.sleep(2)
    lan = input("Co uděláte : jít hledat přátele  ,  rychle utéct  ?")
elif spusteni == "opustit":
    print("Škoda, třeba příště budete mít větší odvahu.") 
    quit()   
else :
    print("Neplatná odpověď, KONEC HRY !")
    quit()

#zasadni rozhodovani ve hre

 
if lan == "1":
    print("Jdete hledat své ztracené přátele, ale víte , že to v této obrovské budově nebude snadné.")
    time.sleep(2)
    print("Vyšel jste z místnosti na chodbu a přemýšlíte kam dál.")
    time.sleep(2)
    pokr = input("Kam dál : prozkoumat sklepení  ,  jít do přízemí  ?")
    if pokr == "1":
        print("Pokračujete chodbou ve sklepení ,ale zatím jste nenarazili.")
        time.sleep(2)
        print("Došli jste až na konec chodby a nic jste neobjevili.")
        time.sleep(2)
        print("Zezadu po chvíli ale slyšíte zvuky něco jako kdyby ťukalo o kyslíkovou bombu a potom také hluboké nadávky. ")
        time.sleep(2)
        print("Jak jste se pomalu vzdaloval od zvuku, tak jste omylem bouchl do stolku a z něho spadla kovová tyč na zem.")
        time.sleep(2)
        wen = input("Jak budete konat : schovat se do armádní skříňky  ,  odvážlivě zařvete ?")
        if wen == "1":
            print("Schoval jste se do skříně a slyšíte jak se neznámý psychopat přibližuje.")
            time.sleep(2)
            print("Jakmile se přiblížil opravdu blízko tak jste zadržel dech a modlil se ať odejde.")
            time.sleep(2)
            print("Šťestí vám přálo a psychopat si vás nevšiml a po chvíli odešel.")
            time.sleep(2)
            print("Vylezl jste ze skříně a vydáte se na přízemní patro ze sklepení.")
            time.sleep(2)
            ign = input("Dále prozkoumat :  přízemí  ,  1.patro ?")
            if ign == "1":
                print("Vyzkoušeli jste hlavní dveře v přízemí, ale jsou zamčené.")
                time.sleep(2)
                print("Prohledáváte přízemí a doufáte, že najdete své přátele nebo alespoň klíče.")
                time.sleep(2)
                print("Po nějaké chvíli narazíte na zabarikádovanou místnost.")
                time.sleep(2)
                print("Snažíte se potichu barikády odstranit, aby jste zjistili co se v místnosti nachází.")
                time.sleep(2)
                print("Barikády se vám podaří odstranit a jdete se podívat co se uvnitř skrývá.")
                time.sleep(2)
                print("Uvnitř sedí svázaní vaši dva přátelé. Jeden má ale nepříjemně poraněnou nohu.")
                time.sleep(2)
                print("Osvobodíte je a pomůžete svému zraněnému kamarádovi")
                time.sleep(2)
                print("Snažíte se co nejrychleji dostat k východu, který jste při prochrázení přízemím zahlédl.")
                time.sleep(2)
                print("Zvládli jste to!  PŘEŽILI jste vaši nejhorší noc v životě  a poté co jste utekli, tak jste v nejbližším městě zavolali policii, aby prozkoumali opuštěnou léčebnu.")
                time.sleep(1)
                print("KONEC HRY")
                quit()
            elif ign == "2":
                print("Jdete po schodech prohledat první patro.")
                time.sleep(2)
                print("Asi po 5-ti minutách uslyšíté zvuky jako by někdo volal o pomoc, ale u toho by měl zacpanou pusu.")
                time.sleep(2)
                print("Nejdříve jste se neodhodlal , ale podlehl jste tlaku a šel zvuky prověřit jestli se nejedná o jednoho z vašich přátel.")
                time.sleep(2)
                print("Opatrně vstupujete do místnosti ze které zvuky vychází i přesto, že si vůbec nejste jisti.")
                time.sleep(2)
                print("Zjistíte, že v místnosti nikdo není. Nic jiného než kazeťák ze kterého zvuky vychází.")
                time.sleep(2)
                print("Další co jen slyšíte jsou kroky za vámi.")
                time.sleep(2)
                print("Byli jste zezadu napadeni a začali jste být dušeni plynem.")
                time.sleep(2)
                print("UMÍRÁTE udušením z nečekaného přepadnutí zezadu.")
                time.sleep(1)
                print("KONEC HRY")
                quit()
            else:
                print("Neplatná odpověď, KONEC HRY !")
            quit()

        elif wen == "2":
            print("Zařval jste na člověka ať se drží dál a nepřibližuje se.")
            time.sleep(2)
            print("Došlo vám že tady hrdinou nebudete a všimnete si, že psychopat se oproti vám rozeběhne.")
            time.sleep(2)
            print("Jelikož jste ve slepé uličce, tak nevíte co dělat.")
            time.sleep(2)
            print("Rozhodnete se vzdát. Psychopat k vám doběhne ve své děsivé masce.")
            time.sleep(2)
            print("Prosíte ho slitování, ale žádné nemá a okamžitě vás dusí plynem ze své bomby.")
            time.sleep(2)
            print("Nedokážete se ubránit a UMÍRÁTE udušením.")
            time.sleep(1)
            print("KONEC HRY")
            quit()
        else :
            print("Neplatná odpověď, KONEC HRY !")
            quit()

    elif pokr == "2":
        print("Jdete rychle na přízemí s domněnkou, že přátelé tam na vás mohou čekat.")
        time.sleep(2)
        print("Vylezl jste po schodech do přízemní místnosti, ale nikoho jste nenašel.")
        time.sleep(2)
        print("Porozhlédl jste se po místnosti a našel jste brýle svého přítele od krve na jednom ze stolků.")
        time.sleep(2)
        print("S velikou obavou a strachem se rozhodujete co dál uděláte.")
        time.sleep(2)
        lou = input("Jak se dál rozhodnete : pokračovat v hledání přátel nebo dostat se ven z léčebny ?")  
        if lou == "1":
            print("Bloudíte dlouho a máte čím dál větší strach, protože máte pocit jako kdyby vás něco následovalo.")  
            time.sleep(2)  
            print("Po dlouhé době jste objevili třetího přítele, ale s prostřelenou hlavou.")
            time.sleep(2)
            print("Oba dva se rozhodnete utéct z budovy (rozbijete vchodové dveře) a v nejbližší obci přivolat pomoc.") 
        elif lou == "2":
            print("Zkusíte hlavní vchodové dveře, ale samozřejmě jsou zamčeny.")
            time.sleep(2)
            print("Oknem víte, že to nepůjde, jelikož mají na sobě mříže.")
            time.sleep(2)
            print("Na recepci si všimnete mapy pro případ požáru s vyznačenými východy. Je sice v rozpadajícím stavu, ale ještě zvládnete zjistit, kde se východy nachází.") 
            time.sleep(2)
            print("Na mapě jsou vyznačené ještě dva další východy, jeden na druhé straně budovy a druhý přes požární schodiště.")
            time.sleep(2)
            print("Musíte si vybrat jaký východ chcete použít.") 
            time.sleep(2)
            esc = input("Který východ : východ na druhé straně  ,  požární schodiště ?")
            if esc == "1":
                print("Sebral jste odvahu a vycházíte přes celou budovu k druhému východu.")
                time.sleep(2)
                print("Měl jste obrovské štěstí , že jste nenarazil ani nespatřil psychopata.")
                time.sleep(2)
                print("Po 10-ti minutovém opatrném průchodu budovou jste dorazil ke dveřím.")
                time.sleep(2)
                print("Doufáte v jediné, že dveře nebudou zamčené či zatrasené z druhé strany, protože máte pocit, že psychopat vám je na stopě.")
                time.sleep(2)
                print("Byla to vaše šťastná chvíle, dveře byly otevřené.")
                time.sleep(2)
                print("Vyběhl jste co nejrychleji to šlo a dal jste se směrem k blízkému městu pro pomoc. PŘEŽIL JSTE vaši nejhorší noc v životě.")
                time.sleep(1)
                print("KONEC HRY")
                quit()
            elif esc == "2":
                print("Vydáte se do druhého patra kde je východ skrz požární schodiště.")
                time.sleep(2)
                print("Po cestě jste zahlédl v prvním patře psychopata jak sestrojuje nějaký zvláštní přístroj.")
                time.sleep(2)
                print("Nevšiml si vás, a tak pokračujete ke schodišti.")
                time.sleep(2)
                print("Dojdete ke schodišti, ale zjistíte, že už je v polorozpadlém stavu.")
                time.sleep(2)
                print("Nechcete se už vracet, a tak opatrně vlezete na schodiště")
                time.sleep(2)
                print("Nejdřive jde vše dle plánu, ale posledních pár metrů od země se moc zapřete o zábradlí a to se přelomí.")
                time.sleep(2)
                print("Padáte z výšky asi 11 metrů. Dopadli jste ošklivě na hlavu a UMÍRÁTE.")
                time.sleep(1)
                print("KONEC HRY")
                quit()
            else:
                print("Neplatná odpověď, KONEC HRY !")
            quit()          
        else:           
            print("Neplatná odpověď, KONEC HRY !")
            quit()
    else:
        print("Neplatná odpověď, KONEC HRY !")
        quit()


elif lan =="2":
    print("Co nejdříve jste se rozutekli, ale tím jak jste byli ve spěchu, tak jste podklouzl na chodbě a nabodl si nohu o rozbitou železnou tyč.")
    time.sleep(2)
    print("Nohu si budete muset ošetřit nebo daleko nedojdete.")
    time.sleep(2)
    pog = input("Co uděláte : ošetřit nohu  ,  pokusit se utéct ?")
    if pog =="1":
        print("Nohu jste si obvázal kusem bílého hadru a přívazal k ní 2 dřevěné tyče na zpevnění")
        time.sleep(2)
        print("Chodí se vám lépe, ale běhat nedokážete.")
        time.sleep(2)
        print("Při cestě k hledání východu jste našel okno s rozbitými mřížemi.")
        time.sleep(2)
        print("Dokulháte k oknu a skáčete ven. Co nejrychleji se šoupete lesem do nejbližšího města.")
        time.sleep(2)
        print("Zbaněle jste zanechal své přátele, ale sotva jste PŘEŽIL tuto hororovou noc.")
        time.sleep(1)
        print("KONEC HRY")
        quit()
    elif pog =="2":
        print("Snažíte se bolest přetrpět a pokračujete na cestě z léčebny")
        time.sleep(2)
        print("Doplazíte se až k východovým dveřím, ale bolest začne být nesnesitelná.")
        time.sleep(2)
        print("Upadnete úplně na zem a nedokážete dále pokračovat.")
        time.sleep(2)
        print("Psychopat vás po stopách krve vypátrá a vysměje se vám do tváře předtím než vás začne dusit plynem.")
        time.sleep(2)
        print("UMÍRÁTE udušením a z léčebny se z původní trojice nedostal ani jeden.") 
        time.sleep(1)
        print("KONEC HRY")
        quit() 
    else:
        print("Neplatná odpověď, KONEC HRY !")
        quit()
else:
    print("Neplatná odpověď, KONEC HRY !")
    quit()


